export enum EVENT {
  OPTIONS_PAGE_OPEN = `GHOST_CHAT_OPTIONS_PAGE_OPEN`,
  APP_OPEN = 'GHOST_CHAT_APP_OPEN',
  NOTIFICATION_PUSH = 'GHOST_CHAT_NOTIFICATION_PUSH',
  NOTIFICATION_CLEAR = 'GHOST_CHAT_NOTIFICATION_CLEAR'
}
